name: Dependency Submission

jobs:
  dependency-submission:
    name: Submit dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@ed408507eac070d1f99cc633dbcf757c94c7933a # v4
      with:
        # Profiler plugins do not expose the dependencies to the runtime, so the versions used for the build
        # do not affect the execution. At the same time, we might need to build plugins for different thirdparty
        # versions, so we intentionally exclude :plugins:* projects from the submitted dependencies
        dependency-graph-exclude-projects: |
          :plugins:.*
