name: Dependency Submission

jobs:
  dependency-submission:
    name: Submit dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@3f131e8634966bd73d06cc69884922b02e6faf92 # v6
      with:
        # Profiler plugins do not expose the dependencies to the runtime, so the versions used for the build
        # do not affect the execution. At the same time, we might need to build plugins for different thirdparty
        # versions, so we intentionally exclude :plugins:* projects from the submitted dependencies
        dependency-graph-exclude-projects: |
          :plugins:.*
